Tensor:张量

Numpy里这个叫array(数组);pytorch里叫tensor(张量)


它们长得一模一样，用法也几乎一样。唯一的区别是：


NumPy Array：只能在 CPU 上跑（老实人，算得慢）。


PyTorch Tensor：可以在 GPU 上跑（穿了钢铁侠战衣，算得飞快）。

In [1]:
#环境自检

import torch
import numpy as np

print("PyTorch 版本:", torch.__version__)
# 如果没报错，打印出了版本号（比如 2.x.x），说明安装成功！

PyTorch 版本: 2.7.1


In [4]:
data = [1,2,3]
#原来的numpy: arr = np.array(data)
tensor = torch.tensor(data)
print(tensor)

#生成随机数
random_tensor = torch.rand(2,3)  # 2行3列的随机数张量
zero_tensor = torch.zeros(2,3)  # 2行3列的零张量
one_tensor = torch.ones(2,3)    # 2行3列的全一张量
print("随机数张量:\n", random_tensor)
print("零张量:\n", zero_tensor)
print("全一张量:\n", one_tensor)
print("张量的形状:", random_tensor.shape)  # 输出张量的形状

tensor([1, 2, 3])
随机数张量:
 tensor([[0.8056, 0.6704, 0.8261],
        [0.7292, 0.3310, 0.9392]])
零张量:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
全一张量:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
张量的形状: torch.Size([2, 3])


In [ ]:
#设备检测: cpu还是gpu
x = torch.tensor([1, 2, 3])
print("当前设备:", x.device) # 输出应该是 cpu

当前设备: cpu


In [6]:
# 2. 【魔法步骤】搬运到 GPU (Mac M芯片)
# 如果你是 Windows/Linux N卡用户，这里写 'cuda'
# 如果你是 Mac M芯片用户，这里写 'mps'
if torch.backends.mps.is_available():
    x_gpu = x.to('mps')
    print("搬运后设备:", x_gpu.device) # 输出应该是 mps:0
    print("原来的 x 还在吗？", x.device) # 还在 CPU，.to() 是返回一个新副本
else:
    print("你的电脑不支持 MPS 加速，只能用 CPU 跑。")

搬运后设备: mps:0
原来的 x 还在吗？ cpu


In [8]:
#***numpy 和 tensor 互转***
# 1. NumPy -> Tensor
np_array = np.array([5, 6, 7])
tensor_from_np = torch.from_numpy(np_array)
print("NumPy 变身:", tensor_from_np)

# 2. Tensor -> NumPy
back_to_np = tensor_from_np.numpy()
print("变回原形:", back_to_np)

# 🚨 警告：如果 Tensor 在 GPU (mps/cuda) 上，必须先搬回 CPU 才能转 NumPy
# x_gpu.numpy() # 这行会报错！
# 正确写法：
# x_gpu.cpu().numpy()

NumPy 变身: tensor([5, 6, 7])
变回原形: [5 6 7]


day1通关: 张量初体验

In [16]:
import torch
import numpy as np

tensor = torch.rand(5, 3)
tensor2 = torch.rand(3,2)
Y = torch.mm(tensor, tensor2)+ torch.ones(2, )
#Y2 = torch.mm(tensor, tensor2)+ torch.ones(2,2 )


print(Y)

print(Y.shape)




tensor([[1.2152, 1.4365],
        [1.6780, 1.8078],
        [2.2421, 2.4994],
        [1.4841, 1.5690],
        [1.4779, 1.7536]])
torch.Size([5, 2])


In [ ]:
#只想给前两行加bias
Y3 = torch.mm(tensor, tensor2)
Y3[:2, :] = Y3[:2, :] + torch.ones(2, ) #行取 0 和 1，列取全部
print(Y3)

tensor([[1.4236, 1.6794],
        [1.3888, 1.5809],
        [0.5656, 0.3919],
        [0.1731, 0.1416],
        [0.2710, 0.1711]])


In [2]:
import torch

# 1. 检查是不是 NVIDIA 显卡 (Mac 上肯定是 False)
print("Is CUDA available?", torch.cuda.is_available())

# 2. 检查是不是 Mac M芯片加速 (MPS)
# 这才是你应该关注的！如果是 True，说明你的 Mac 显卡起飞了！
print("Is MPS available?", torch.backends.mps.is_available())


Is CUDA available? False
Is MPS available? True
